version: '3'

services:
  vue:
    build: ./vue
    volumes:
      - ./vue/app:/srv/front/src/app
    ports:
      - "8083:8080"
    tty: true
    working_dir: /srv/front/src/app
    command: yarn build

  nginx:
    build: ./nginx
    ports:
        - '9999:80'
    volumes:
        - ./vue/app/:/var/www/html/